# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Poochie' do
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'EPDeckView'
end

target 'PoochieTests' do
    
    
end

target 'PoochieUITests' do
    
end


