# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Poochie' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poochie

  target 'PoochieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoochieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
